---
# .github/workflows/immune.yml
name: Governance Immune System
on:
  workflow_call:

jobs:
  inspect-and-lint:
    name: Inspect and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from calling repository
        uses: actions/checkout@v4

      # --- 修正点 ---: MegaLinterを実行するステップを追加
      - name: Run MegaLinter
        uses: oxsecurity/megalinter@v7
        env:
          # 呼び出し元のリポジトリ全体をチェック対象とする
          VALIDATE_ALL_CODEBASE: true
          # governanceリポジトリにある設定ファイルを参照させる
          MEGALINTER_CONFIG: "https://raw.githubusercontent.com/mikieto/governance/main/.megalinter.yml"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

